// eslint.config.js — ESLint v9 flat config
export default [
    {
        files: ["frontend/js/**/*.js"],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: "module",
            globals: {
                window: "readonly",
                document: "readonly",
                console: "readonly",
                fetch: "readonly",
                setTimeout: "readonly",
                clearTimeout: "readonly",
                setInterval: "readonly",
                clearInterval: "readonly",
                alert: "readonly",
                confirm: "readonly",
                navigator: "readonly",
                location: "readonly",
                localStorage: "readonly",
                sessionStorage: "readonly",
                FormData: "readonly",
                URLSearchParams: "readonly",
                Promise: "readonly",
                Map: "readonly",
                Set: "readonly",
                Error: "readonly",
                JSON: "readonly",
                Math: "readonly",
                Date: "readonly",
                parseInt: "readonly",
                parseFloat: "readonly",
                isNaN: "readonly",
                isFinite: "readonly",
                URL: "readonly",
                Request: "readonly",
                Response: "readonly",
                Headers: "readonly",
                AbortController: "readonly",
                EventSource: "readonly",
                MutationObserver: "readonly",
                ResizeObserver: "readonly",
                IntersectionObserver: "readonly",
                // Bootstrap / Tabler globals
                bootstrap: "readonly",
            },
        },
        rules: {
            "no-unused-vars": "off",
            "no-undef": "off",
            "no-console": "off",
            "semi": "off",
            "no-duplicate-imports": "error",
        },
        ignores: ["frontend/js/technical-analysis.js"],
    },
];
